# RedELK Nginx Redirector Filebeat Configuration
# Ships Nginx access and error logs to RedELK

filebeat.inputs:
# Nginx Access Logs
- type: filestream
  id: nginx-access
  enabled: true
  paths:
    - /var/log/nginx/access.log
    - /var/log/nginx/*access*.log
  exclude_files: ['\.gz$', '\.bz2$', '\.zip$']
  exclude_lines: ['ELB-HealthChecker', 'Amazon-Route53-Health-Check']
  fields:
    infra:
      log:
        type: redirtraffic
    redir:
      program: nginx
  fields_under_root: true

# Nginx Error Logs
- type: filestream
  id: nginx-error
  enabled: true
  paths:
    - /var/log/nginx/error.log
    - /var/log/nginx/*error*.log
  exclude_files: ['\.gz$', '\.bz2$', '\.zip$']
  fields:
    infra:
      log:
        type: redirerror
    redir:
      program: nginx
  fields_under_root: true

# Output to RedELK Logstash
output.logstash:
  hosts: ['REDELK_HOST:5044']
  ssl.enabled: true
  ssl.verification_mode: certificate
  ssl.certificate_authorities: ['/etc/filebeat/certs/redelk-ca.crt']

# Processors
processors:
  - add_host_metadata: ~
  - add_fields:
      target: ''
      fields:
        role: redir
  - add_tags:
      tags: ['redelk', 'nginx']

# Template management
setup.template.enabled: false

# Logging
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
