name: redelk
version: '3.0.0'
summary: Red Team SIEM - Track and alarm on Blue Team activities
description: |
  RedELK is a comprehensive Red Team SIEM for tracking operations and
  detecting Blue Team investigation activities.
  
  Features:
  - Modern Python installer with interactive wizard
  - Support for multiple C2 frameworks (Cobalt Strike, Sliver, PoshC2)
  - ELK Stack 8.x integration
  - BloodHound CE integration
  - Real-time health monitoring
  - Automated certificate generation
  - Comprehensive dashboards and visualizations
  
  Quick Start:
    sudo snap install redelk
    sudo redelk.install --quickstart
    redelk.status
  
  This snap requires Docker to be installed separately.

grade: stable
confinement: classic
base: core22

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  redelk:
    command: usr/bin/redelk
    plugs:
      - docker
      - network
      - network-bind
      
  install:
    command: usr/bin/redelk-install
    plugs:
      - docker
      - network
      - network-bind
      - network-control
      
  install-agent:
    command: usr/bin/redelk-install-agent
    plugs:
      - network
      - network-bind
      
  cert-gen:
    command: usr/share/redelk/scripts/generate-certificates.py
    plugs:
      - network
      
  health:
    command: usr/share/redelk/scripts/health-check.py
    plugs:
      - docker
      - network

parts:
  redelk:
    plugin: dump
    source: .
    source-type: git
    organize:
      install.py: usr/bin/redelk-install
      install-agent.py: usr/bin/redelk-install-agent
      redelk: usr/bin/redelk
      scripts/*: usr/share/redelk/scripts/
      elkserver/*: usr/share/redelk/elkserver/
      c2servers/*: usr/share/redelk/c2servers/
      redirs/*: usr/share/redelk/redirs/
      certs/*: usr/share/redelk/certs/
      docs/*: usr/share/doc/redelk/
      Makefile: usr/share/redelk/Makefile
      env.template: usr/share/redelk/env.template
      README.md: usr/share/doc/redelk/README.md
      CHANGELOG.md: usr/share/doc/redelk/CHANGELOG.md
    stage-packages:
      - python3
      - python3-pip
      - openssl
      - apache2-utils
      - curl
      - wget
    override-build: |
      craftctl default
      # Install Python dependencies in snap
      pip3 install --target=$CRAFT_PART_INSTALL/usr/lib/python3/dist-packages rich click

